=== roumaissafekar/tp2_MTI/M1.dtd
<!ELEMENT M1(etudiant*)>
<!ELEMENT etudiant (Identite,Moy)>
<!ELEMENT Identite (Matricule,Nom,Prenom)>
<!ELEMENTMoy (MoyS1,MoyS2,MoyAnnuel,CreditS1,CreditS2,Unite)>
<!ELEMENT Matricule (#PCDATA)>
<!ELEMENT Nom (#PCDATA)>
<!ELEMENT Prenom (#PCDATA)>
<!ELEMENT MoyS1 (#PCDATA)>
<!ELEMENT MoyS2 (#PCDATA)>
<!ELEMENT MoyAnnuel (#PCDATA)>
<!ELEMENT CreditS1 (#PCDATA)>
<!ELEMENT CreditS2 (#PCDATA)>
<!ELEMENT Unite (#PCDATA)>

=== roumaissafekar/tp2_MTI/M1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE M1 SYSTEM "M1.dtd">
<?xml-stylesheet type="text/xsl" href="M1.xsl"?> 
<M1>
<etudiant>
<Identite>
<Matricule>Q14M121</Matricule>
<Nom>ZIANE</Nom>
<Prenom>BILAL</Prenom>
</Identite>
<Moy>
<MoyS1>12.78</MoyS1>
<MoyS2>12.87</MoyS2>
<MoyAnnuel>12.83</MoyAnnuel>
<CreditS1>30</CreditS1>
<CreditS2>30</CreditS2>
<Unite>Oui</Unite>
</Moy>
</etudiant>
<etudiant>
<Identite>
<Matricule>Q14M120</Matricule>
<Nom>ZITOUNI</Nom>
<Prenom>SOUMIA</Prenom>
</Identite>
<Moy>
<MoyS1>12.01</MoyS1>
<MoyS2>13.45</MoyS2>
<MoyAnnuel>12.73</MoyAnnuel>
<CreditS1>30</CreditS1>
<CreditS2>30</CreditS2>
<Unite>Oui</Unite>
</Moy>
</etudiant>
<etudiant>
<Identite>
<Matricule>Q14M125</Matricule>
<Nom>ZEGHDANE</Nom>
<Prenom>HOUSSAM</Prenom>
</Identite>
<Moy>
<MoyS1>13.63</MoyS1>
<MoyS2>11.52</MoyS2>
<MoyAnnuel>12.58</MoyAnnuel>
<CreditS1>30</CreditS1>
<CreditS2>30</CreditS2>
<Unite>Oui</Unite>
</Moy>
</etudiant>
<etudiant>
<Identite>
<Matricule>Q14M122</Matricule>
<Nom>ZIANE</Nom>
<Prenom>MEZIANE</Prenom>
</Identite>
<Moy>
<MoyS1>12.72</MoyS1>
<MoyS2>11.93</MoyS2>
<MoyAnnuel>12.33</MoyAnnuel>
<CreditS1>30</CreditS1>
<CreditS2>30</CreditS2>
<Unite>Oui</Unite>
</Moy>
</etudiant>
<etudiant>
<Identite>
<Matricule>Q14M152</Matricule>
<Nom>TALEB</Nom>
<Prenom>ASMA</Prenom>
</Identite>
<Moy>
<MoyS1>14.73</MoyS1>
<MoyS2> 9.90</MoyS2>
<MoyAnnuel>12.32</MoyAnnuel>
<CreditS1>30</CreditS1>
<CreditS2>21</CreditS2>
<Unite>Oui</Unite>
</Moy>
</etudiant>
<etudiant>
<Identite>
<Matricule>Q14M141</Matricule>
<Nom>TOUATI</Nom>
<Prenom>MOHAMED</Prenom>
</Identite>
<Moy>
<MoyS1>11.99</MoyS1>
<MoyS2>10.37</MoyS2>
<MoyAnnuel>11.18</MoyAnnuel>
<CreditS1>30</CreditS1>
<CreditS2>30</CreditS2>
<Unite>Oui</Unite>
</Moy>
</etudiant>
<etudiant>
<Identite>
<Matricule>Q14M126</Matricule>
<Nom>ZEGADI</Nom>
<Prenom>AMEL</Prenom>
</Identite>
<Moy>
<MoyS1>11.04</MoyS1>
<MoyS2>11.25</MoyS2>
<MoyAnnuel>11.15</MoyAnnuel>
<CreditS1>30</CreditS1>
<CreditS2>30</CreditS2>
<Unite>Oui</Unite>
</Moy>
</etudiant>
<etudiant>
<Identite>
<Matricule>Q14M123</Matricule>
<Nom>ZIANE</Nom>
<Prenom>AMIRA</Prenom>
</Identite>
<Moy>
<MoyS1>10.15</MoyS1>
<MoyS2>11.91</MoyS2>
<MoyAnnuel>11.03</MoyAnnuel>
<CreditS1>30</CreditS1>
<CreditS2>30</CreditS2>
<Unite>Oui</Unite>
</Moy>
</etudiant>
<etudiant>
<Identite>
<Matricule>Q14M135</Matricule>
<Nom>YAHIAOUI</Nom>
<Prenom>MOHAMED</Prenom>
</Identite>
<Moy>
<MoyS1>11.32</MoyS1>
<MoyS2>10.56</MoyS2>
<MoyAnnuel>10.94</MoyAnnuel>
<CreditS1>30</CreditS1>
<CreditS2>30</CreditS2>
<Unite>Oui</Unite>
</Moy>
</etudiant>
<etudiant>
<Identite>
<Matricule>Q14M124</Matricule>
<Nom>ZERARI</Nom>
<Prenom>OUASSILA</Prenom>
</Identite>
<Moy>
<MoyS1>10.20</MoyS1>
<MoyS2>11.65</MoyS2>
<MoyAnnuel>10.93</MoyAnnuel>
<CreditS1>30</CreditS1>
<CreditS2>30</CreditS2>
<Unite>Oui</Unite>
</Moy>
</etudiant>
<etudiant>
<Identite>
<Matricule>Q14M168</Matricule>
<Nom>SENANI</Nom>
<Prenom>HAYET</Prenom>
</Identite>
<Moy>
<MoyS1>12.70</MoyS1>
<MoyS2> 9.12</MoyS2>
<MoyAnnuel>10.91</MoyAnnuel>
<CreditS1>30</CreditS1>
<CreditS2>3</CreditS2>
<Unite>Oui</Unite>
</Moy>
</etudiant>
<etudiant>
<Identite>
<Matricule>Q14M143</Matricule>
<Nom>TIGRINE</Nom>
<Prenom>AYOUB</Prenom>
</Identite>
<Moy>
<MoyS1>11.30</MoyS1>
<MoyS2>10.30</MoyS2>
<MoyAnnuel>10.8</MoyAnnuel>
<CreditS1>30</CreditS1>
<CreditS2>30</CreditS2>
<Unite>Oui</Unite>
</Moy>
</etudiant>
<etudiant>
<Identite>
<Matricule>Q14M158</Matricule>
<Nom>SOBAIHI</Nom>
<Prenom>FAHEM</Prenom>
</Identite>
<Moy>
<MoyS1>11.97</MoyS1>
<MoyS2> 9.49</MoyS2>
<MoyAnnuel>10.73</MoyAnnuel>
<CreditS1>30</CreditS1>
<CreditS2>23</CreditS2>
<Unite>Non</Unite>
</Moy>
</etudiant>
<etudiant>
<Identite>
<Matricule>Q14M128</Matricule>
<Nom>ZAIR</Nom>
<Prenom>KAHINA</Prenom>
</Identite>
<Moy>
<MoyS1>10.57</MoyS1>
<MoyS2>10.84</MoyS2>
<MoyAnnuel>10.71</MoyAnnuel>
<CreditS1>30</CreditS1>
<CreditS2>30</CreditS2>
<Unite>Oui</Unite>
</Moy>
</etudiant>
<etudiant>
<Identite>
<Matricule>Q14M132</Matricule>
<Nom>YOUCEFI</Nom>
<Prenom>SORAYA</Prenom>
</Identite>
<Moy>
<MoyS1>10.54</MoyS1>
<MoyS2>10.71</MoyS2>
<MoyAnnuel>10.63</MoyAnnuel>
<CreditS1>30</CreditS1>
<CreditS2>30</CreditS2>
<Unite>Oui</Unite>
</Moy>
</etudiant>
<etudiant>
<Identite>
<Matricule>Q14M142</Matricule>
<Nom>TOUAMA</Nom>
<Prenom>YAZID</Prenom>
</Identite>
<Moy>
<MoyS1>10.69</MoyS1>
<MoyS2>10.35</MoyS2>
<MoyAnnuel>10.52</MoyAnnuel>
<CreditS1>30</CreditS1>
<CreditS2>30</CreditS2>
<Unite>Oui</Unite>
</Moy>
</etudiant>
<etudiant>
<Identite>
<Matricule>Q14M127</Matricule>
<Nom>ZAKNOUN</Nom>
<Prenom>ANOUAR</Prenom>
</Identite>
<Moy>
<MoyS1>10.12</MoyS1>
<MoyS2>10.87</MoyS2>
<MoyAnnuel>10.5</MoyAnnuel>
<CreditS1>30</CreditS1>
<CreditS2>30</CreditS2>
<Unite>Oui</Unite>
</Moy>
</etudiant>
<etudiant>
<Identite>
<Matricule>Q14M136</Matricule>
<Nom>TOUMIAT</Nom>
<Prenom>SARAH</Prenom>
</Identite>
<Moy>
<MoyS1>10.51</MoyS1>
<MoyS2>10.47</MoyS2>
<MoyAnnuel>10.49</MoyAnnuel>
<CreditS1>30</CreditS1>
<CreditS2>30</CreditS2>
<Unite>Oui</Unite>
</Moy>
</etudiant>
<etudiant>
<Identite>
<Matricule>Q14M130</Matricule>
<Nom>ZAFER</Nom>
<Prenom>SOFIA</Prenom>
</Identite>
<Moy>
<MoyS1>10.11</MoyS1>
<MoyS2>10.80</MoyS2>
<MoyAnnuel>10.46</MoyAnnuel>
<CreditS1>30</CreditS1>
<CreditS2>30</CreditS2>
<Unite>Oui</Unite>
</Moy>
</etudiant>
<etudiant>
<Identite>
<Matricule>Q14M139</Matricule>
<Nom>TOUATI</Nom>
<Prenom>ALI</Prenom>
</Identite>
<Moy>
<MoyS1>10.35</MoyS1>
<MoyS2>10.40</MoyS2>
<MoyAnnuel>10.38</MoyAnnuel>
<CreditS1>30</CreditS1>
<CreditS2>30</CreditS2>
<Unite>Oui</Unite>
</Moy>
</etudiant>
<etudiant>
<Identite>
<Matricule>Q14M129</Matricule>
<Nom>ZAIDI</Nom>
<Prenom>IBTISSAM</Prenom>
</Identite>
<Moy>
<MoyS1> 9.94</MoyS1>
<MoyS2>10.82</MoyS2>
<MoyAnnuel>10.38</MoyAnnuel>
<CreditS1>24</CreditS1>
<CreditS2>30</CreditS2>
<Unite>Non</Unite>
</Moy>
</etudiant>
<etudiant>
<Identite>
<Matricule>Q14M134</Matricule>
<Nom>TOUMINE</Nom>
<Prenom>AMEL</Prenom>
</Identite>
<Moy>
<MoyS1>10.18</MoyS1>
<MoyS2>10.56</MoyS2>
<MoyAnnuel>10.37</MoyAnnuel>
<CreditS1>30</CreditS1>
<CreditS2>30</CreditS2>
<Unite>Oui</Unite>
</Moy>
</etudiant>
<etudiant>
<Identite>
<Matricule>Q14M140</Matricule>
<Nom>TOUATI</Nom>
<Prenom>KHOULA</Prenom>
</Identite>
<Moy>
<MoyS1>10.31</MoyS1>
<MoyS2>10.39</MoyS2>
<MoyAnnuel>10.35</MoyAnnuel>
<CreditS1>30</CreditS1>
<CreditS2>30</CreditS2>
<Unite>Oui</Unite>
</Moy>
</etudiant>
<etudiant>
<Identite>
<Matricule>Q14M137</Matricule>
<Nom>TOUMIAT</Nom>
<Prenom>HAMID</Prenom>
</Identite>
<Moy>
<MoyS1>10.18</MoyS1>
<MoyS2>10.43</MoyS2>
<MoyAnnuel>10.31</MoyAnnuel>
<CreditS1>30</CreditS1>
<CreditS2>30</CreditS2>
<Unite>Oui</Unite>
</Moy>
</etudiant>
<etudiant>
<Identite>
<Matricule>Q14M131</Matricule>
<Nom>ZAAMOUCHE</Nom>
<Prenom>HOCINE</Prenom>
</Identite>
<Moy>
<MoyS1> 9.84</MoyS1>
<MoyS2>10.72</MoyS2>
<MoyAnnuel>10.28</MoyAnnuel>
<CreditS1>6</CreditS1>
<CreditS2>30</CreditS2>
<Unite>Oui</Unite>
</Moy>
</etudiant>
<etudiant>
<Identite>
<Matricule>Q14M133</Matricule>
<Nom>YAHYAOUI</Nom>
<Prenom>ROUMAISSA</Prenom>
</Identite>
<Moy>
<MoyS1> 9.86</MoyS1>
<MoyS2>10.66</MoyS2>
<MoyAnnuel>10.26</MoyAnnuel>
<CreditS1>22</CreditS1>
<CreditS2>30</CreditS2>
<Unite>Non</Unite>
</Moy>
</etudiant>
<etudiant>
<Identite>
<Matricule>Q14M151</Matricule>
<Nom>TAIABI</Nom>
<Prenom>SARA</Prenom>
</Identite>
<Moy>
<MoyS1>10.62</MoyS1>
<MoyS2> 9.90</MoyS2>
<MoyAnnuel>10.26</MoyAnnuel>
<CreditS1>30</CreditS1>
<CreditS2>22</CreditS2>
<Unite>Oui</Unite>
</Moy>
</etudiant>
<etudiant>
<Identite>
<Matricule>Q14M155</Matricule>
<Nom>TAHIRI</Nom>
<Prenom>FATMA</Prenom>
</Identite>
<Moy>
<MoyS1>10.74</MoyS1>
<MoyS2> 9.78</MoyS2>
<MoyAnnuel>10.26</MoyAnnuel>
<CreditS1>30</CreditS1>
<CreditS2>17</CreditS2>
<Unite>Non</Unite>
</Moy>
</etudiant>
<etudiant>
<Identite>
<Matricule>Q14M156</Matricule>
<Nom>TABOURI</Nom>
<Prenom>OUSSAMA</Prenom>
</Identite>
<Moy>
<MoyS1>10.85</MoyS1>
<MoyS2> 9.56</MoyS2>
<MoyAnnuel>10.21</MoyAnnuel>
<CreditS1>30</CreditS1>
<CreditS2>7</CreditS2>
<Unite>Oui</Unite>
</Moy>
</etudiant>
<etudiant>
<Identite>
<Matricule>Q14M150</Matricule>
<Nom>TALI</Nom>
<Prenom>OUSSAMA</Prenom>
</Identite>
<Moy>
<MoyS1>10.46</MoyS1>
<MoyS2> 9.93</MoyS2>
<MoyAnnuel>10.2</MoyAnnuel>
<CreditS1>30</CreditS1>
<CreditS2>7</CreditS2>
<Unite>Oui</Unite>
</Moy>
</etudiant>
<etudiant>
<Identite>
<Matricule>Q14M180</Matricule>
<Nom>SALMI</Nom>
<Prenom>SIHAM</Prenom>
</Identite>
<Moy>
<MoyS1>11.29</MoyS1>
<MoyS2> 8.83</MoyS2>
<MoyAnnuel>10.06</MoyAnnuel>
<CreditS1>30</CreditS1>
<CreditS2>17</CreditS2>
<Unite>Oui</Unite>
</Moy>
</etudiant>
<etudiant>
<Identite>
<Matricule>Q14M197</Matricule>
<Nom>REZKI</Nom>
<Prenom>SOUNIA</Prenom>
</Identite>
<Moy>
<MoyS1>11.68</MoyS1>
<MoyS2> 8.40</MoyS2>
<MoyAnnuel>10.04</MoyAnnuel>
<CreditS1>30</CreditS1>
<CreditS2>12</CreditS2>
<Unite>Oui</Unite>
</Moy>
</etudiant>
<etudiant>
<Identite>
<Matricule>Q14M149</Matricule>
<Nom>TAMAHDJOUBT</Nom>
<Prenom>ABDELBASSET</Prenom>
</Identite>
<Moy>
<MoyS1>10.01</MoyS1>
<MoyS2> 9.98</MoyS2>
<MoyAnnuel>10</MoyAnnuel>
<CreditS1>30</CreditS1>
<CreditS2>6</CreditS2>
<Unite>Non</Unite>
</Moy>
</etudiant>
<etudiant>
<Identite>
<Matricule>Q14M166</Matricule>
<Nom>SERIR</Nom>
<Prenom>AMEL</Prenom>
</Identite>
<Moy>
<MoyS1>10.79</MoyS1>
<MoyS2> 9.21</MoyS2>
<MoyAnnuel>10</MoyAnnuel>
<CreditS1>30</CreditS1>
<CreditS2>1</CreditS2>
<Unite>Oui</Unite>
</Moy>
</etudiant>
<etudiant>
<Identite>
<Matricule>Q14M144</Matricule>
<Nom>TEMINE</Nom>
<Prenom>HAKIMA</Prenom>
</Identite>
<Moy>
<MoyS1> 9.67</MoyS1>
<MoyS2>10.22</MoyS2>
<MoyAnnuel>9.95</MoyAnnuel>
