=== roumaissafekar/tp2_MTI/mushaf.dtd
<!ELEMENT mushaf (sura*)>
<!ELEMENT sura (aya*)>
<!ATTLIST  sura nb_aya CDATA #REQUIRED>
<!ATTLIST   sura name CDATA #REQUIRED>
<!ATTLIST   sura id CDATA #REQUIRED>
<!ELEMENT aya (#PCDATA)>
<!ATTLIST   aya id CDATA #REQUIRED>

=== roumaissafekar/tp2_MTI/mushaf-amma1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mushaf SYSTEM "mushaf.dtd">
<?xml-stylesheet type="text/xsl" href="mushaf-index..xsl"?>
<mushaf>
	<sura nb_aya="40" id="78" name="النبأ">
  <aya id="1">
   عَمَّ يَتَسَاءلُونَ
  </aya>
		<aya id="2">
   عَنِ النَّبَإِ الْعَظِيمِ
  </aya>
		<aya id="3">
   الَّذِي هُمْ فِيهِ مُخْتَلِفُونَ
  </aya>
		<aya id="4">
   كَلَّا سَيَعْلَمُونَ
  </aya>
		<aya id="5">
   ثُمَّ كَلَّا سَيَعْلَمُونَ
  </aya>
		<aya id="6">
   أَلَمْ نَجْعَلِ الْأَرْضَ مِهَادًا
  </aya>
		<aya id="7">
   وَالْجِبَالَ أَوْتَادًا
  </aya>
		<aya id="8">
   وَخَلَقْنَاكُمْ أَزْوَاجًا
  </aya>
		<aya id="9">
   وَجَعَلْنَا نَوْمَكُمْ سُبَاتًا
  </aya>
		<aya id="10">
   وَجَعَلْنَا اللَّيْلَ لِبَاسًا
  </aya>
		<aya id="11">
   وَجَعَلْنَا النَّهَارَ مَعَاشًا
  </aya>
		<aya id="12">
   وَبَنَيْنَا فَوْقَكُمْ سَبْعًا شِدَادًا
  </aya>
		<aya id="13">
   وَجَعَلْنَا سِرَاجًا وَهَّاجًا
  </aya>
		<aya id="14">
   وَأَنزَلْنَا مِنَ الْمُعْصِرَاتِ مَاء ثَجَّاجًا
  </aya>
		<aya id="15">
   لِنُخْرِجَ بِهِ حَبًّا وَنَبَاتًا
  </aya>
		<aya id="16">
   وَجَنَّاتٍ أَلْفَافًا
  </aya>
		<aya id="17">
   إِنَّ يَوْمَ الْفَصْلِ كَانَ مِيقَاتًا
  </aya>
		<aya id="18">
   يَوْمَ يُنفَخُ فِي الصُّورِ فَتَأْتُونَ أَفْوَاجًا
  </aya>
		<aya id="19">
   وَفُتِحَتِ السَّمَاء فَكَانَتْ أَبْوَابًا
  </aya>
		<aya id="20">
   وَسُيِّرَتِ الْجِبَالُ فَكَانَتْ سَرَابًا
  </aya>
		<aya id="21">
   إِنَّ جَهَنَّمَ كَانَتْ مِرْصَادًا
  </aya>
		<aya id="22">
   لِلْطَّاغِينَ مَآبًا
  </aya>
		<aya id="23">
   لَابِثِينَ فِيهَا أَحْقَابًا
  </aya>
		<aya id="24">
   لَّا يَذُوقُونَ فِيهَا بَرْدًا وَلَا شَرَابًا
  </aya>
		<aya id="25">
   إِلَّا حَمِيمًا وَغَسَّاقًا
  </aya>
		<aya id="26">
   جَزَاء وِفَاقًا
  </aya>
		<aya id="27">
   إِنَّهُمْ كَانُوا لَا يَرْجُونَ حِسَابًا
  </aya>
		<aya id="28">
   وَكَذَّبُوا بِآيَاتِنَا كِذَّابًا
  </aya>
		<aya id="29">
   وَكُلَّ شَيْءٍ أَحْصَيْنَاهُ كِتَابًا
  </aya>
		<aya id="30">
   فَذُوقُوا فَلَن نَّزِيدَكُمْ إِلَّا عَذَابًا
  </aya>
		<aya id="31">
   إِنَّ لِلْمُتَّقِينَ مَفَازًا
  </aya>
		<aya id="32">
   حَدَائِقَ وَأَعْنَابًا
  </aya>
		<aya id="33">
   وَكَوَاعِبَ أَتْرَابًا
  </aya>
		<aya id="34">
   وَكَأْسًا دِهَاقًا
  </aya>
		<aya id="35">
   لَّا يَسْمَعُونَ فِيهَا لَغْوًا وَلَا كِذَّابًا
  </aya>
		<aya id="36">
   جَزَاء مِّن رَّبِّكَ عَطَاء حِسَابًا
  </aya>
		<aya id="37">
   رَبِّ السَّمَاوَاتِ وَالْأَرْضِ وَمَا بَيْنَهُمَا الرحْمَنِ لَا يَمْلِكُونَ مِنْهُ خِطَابًا
  </aya>
		<aya id="38">
   يَوْمَ يَقُومُ الرُّوحُ وَالْمَلَائِكَةُ صَفًّا لَّا يَتَكَلَّمُونَ إِلَّا مَنْ أَذِنَ لَهُ الرحْمَنُ وَقَالَ صَوَابًا
  </aya>
		<aya id="39">
   ذَلِكَ الْيَوْمُ الْحَقُّ فَمَن شَاء اتَّخَذَ إِلَى رَبِّهِ مَآبًا
  </aya>
		<aya id="40">
   إِنَّا أَنذَرْنَاكُمْ عَذَابًا قَرِيبًا يَوْمَ يَنظُرُ الْمَرْءُ مَا قَدَّمَتْ يَدَاهُ وَيَقُولُ الْكَافِرُ يَا لَيْتَنِي كُنتُ تُرَابًا 
  </aya>
	</sura>
	<sura nb_aya="46" id="79" name="النازعات">
		<aya id="1">
   وَالنَّازِعَاتِ غَرْقًا
  </aya>
		<aya id="2">
   وَالنَّاشِطَاتِ نَشْطًا
  </aya>
		<aya id="3">
   وَالسَّابِحَاتِ سَبْحًا
  </aya>
		<aya id="4">
   فَالسَّابِقَاتِ سَبْقًا
  </aya>
		<aya id="5">
   فَالْمُدَبِّرَاتِ أَمْرًا
  </aya>
		<aya id="6">
   يَوْمَ تَرْجُفُ الرَّاجِفَةُ
  </aya>
		<aya id="7">
   تَتْبَعُهَا الرَّادِفَةُ
  </aya>
		<aya id="8">
   قُلُوبٌ يَوْمَئِذٍ وَاجِفَةٌ
  </aya>
		<aya id="9">
   أَبْصَارُهَا خَاشِعَةٌ
  </aya>
		<aya id="10">
   يَقُولُونَ أَئِنَّا لَمَرْدُودُونَ فِي الْحَافِرَةِ
  </aya>
		<aya id="11">
   أَئِذَا كُنَّا عِظَامًا نَّخِرَةً
  </aya>
		<aya id="12">
   قَالُوا تِلْكَ إِذًا كَرَّةٌ خَاسِرَةٌ
  </aya>
		<aya id="13">
   فَإِنَّمَا هِيَ زَجْرَةٌ وَاحِدَةٌ
  </aya>
		<aya id="14">
   فَإِذَا هُم بِالسَّاهِرَةِ
  </aya>
		<aya id="15">
   هَلْ أتَاكَ حَدِيثُ مُوسَى
  </aya>
		<aya id="16">
   إِذْ نَادَاهُ رَبُّهُ بِالْوَادِ الْمُقَدَّسِ طُوًى
  </aya>
		<aya id="17">
   اذْهَبْ إِلَى فِرْعَوْنَ إِنَّهُ طَغَى
  </aya>
		<aya id="18">
   فَقُلْ هَل لَّكَ إِلَى أَن تَزَكَّى
  </aya>
		<aya id="19">
   وَأَهْدِيَكَ إِلَى رَبِّكَ فَتَخْشَى
  </aya>
		<aya id="20">
   فَأَرَاهُ الْآيَةَ الْكُبْرَى
  </aya>
		<aya id="21">
   فَكَذَّبَ وَعَصَى
  </aya>
		<aya id="22">
   ثُمَّ أَدْبَرَ يَسْعَى
  </aya>
		<aya id="23">
   فَحَشَرَ فَنَادَى
  </aya>
		<aya id="24">
   فَقَالَ أَنَا رَبُّكُمُ الْأَعْلَى
  </aya>
		<aya id="25">
   فَأَخَذَهُ اللَّهُ نَكَالَ الْآخِرَةِ وَالْأُولَى
  </aya>
		<aya id="26">
   إِنَّ فِي ذَلِكَ لَعِبْرَةً لِّمَن يَخْشَى
  </aya>
		<aya id="27">
   أَأَنتُمْ أَشَدُّ خَلْقًا أَمِ السَّمَاء بَنَاهَا
  </aya>
		<aya id="28">
   رَفَعَ سَمْكَهَا فَسَوَّاهَا
  </aya>
		<aya id="29">
   وَأَغْطَشَ لَيْلَهَا وَأَخْرَجَ ضُحَاهَا
  </aya>
		<aya id="30">
   وَالْأَرْضَ بَعْدَ ذَلِكَ دَحَاهَا
  </aya>
		<aya id="31">
   أَخْرَجَ مِنْهَا مَاءهَا وَمَرْعَاهَا
  </aya>
		<aya id="32">
   وَالْجِبَالَ أَرْسَاهَا
  </aya>
		<aya id="33">
   مَتَاعًا لَّكُمْ وَلِأَنْعَامِكُمْ
  </aya>
		<aya id="34">
   فَإِذَا جَاءتِ الطَّامَّةُ الْكُبْرَى
  </aya>
		<aya id="35">
   يَوْمَ يَتَذَكَّرُ الْإِنسَانُ مَا سَعَى
  </aya>
		<aya id="36">
   وَبُرِّزَتِ الْجَحِيمُ لِمَن يَرَى
  </aya>
		<aya id="37">
   فَأَمَّا مَن طَغَى
  </aya>
		<aya id="38">
   وَآثَرَ الْحَيَاةَ الدُّنْيَا
  </aya>
		<aya id="39">
   فَإِنَّ الْجَحِيمَ هِيَ الْمَأْوَى
  </aya>
		<aya id="40">
   وَأَمَّا مَنْ خَافَ مَقَامَ رَبِّهِ وَنَهَى النَّفْسَ عَنِ الْهَوَى
  </aya>
		<aya id="41">
   فَإِنَّ الْجَنَّةَ هِيَ الْمَأْوَى
  </aya>
		<aya id="42">
   يَسْأَلُونَكَ عَنِ السَّاعَةِ أَيَّانَ مُرْسَاهَا
  </aya>
		<aya id="43">
   فِيمَ أَنتَ مِن ذِكْرَاهَا
  </aya>
		<aya id="44">
   إِلَى رَبِّكَ مُنتَهَاهَا
  </aya>
		<aya id="45">
   إِنَّمَا أَنتَ مُنذِرُ مَن يَخْشَاهَا
  </aya>
		<aya id="46">
   كَأَنَّهُمْ يَوْمَ يَرَوْنَهَا لَمْ يَلْبَثُوا إِلَّا عَشِيَّةً أَوْ ضُحَاهَا
  </aya>
	</sura>
	<sura nb_aya="42" id="80" name="عبس">
		<aya id="1">
   عَبَسَ وَتَوَلَّى
  </aya>
		<aya id="2">
   أَن جَاءهُ الْأَعْمَى
  </aya>
		<aya id="3">
   وَمَا يُدْرِيكَ لَعَلَّهُ يَزَّكَّى
  </aya>
		<aya id="4">
   أَوْ يَذَّكَّرُ فَتَنفَعَهُ الذِّكْرَى
  </aya>
		<aya id="5">
   أَمَّا مَنِ اسْتَغْنَى
  </aya>
		<aya id="6">
   فَأَنتَ لَهُ تَصَدَّى
  </aya>
		<aya id="7">
   وَمَا عَلَيْكَ أَلَّا يَزَّكَّى
  </aya>
		<aya id="8">
   وَأَمَّا مَن جَاءكَ يَسْعَى
  </aya>
		<aya id="9">
   وَهُوَ يَخْشَى
  </aya>
		<aya id="10">
   فَأَنتَ عَنْهُ تَلَهَّى
  </aya>
		<aya id="11">
   كَلَّا إِنَّهَا تَذْكِرَةٌ
  </aya>
		<aya id="12">
   فَمَن شَاء ذَكَرَهُ
  </aya>
		<aya id="13">
   فِي صُحُفٍ مُّكَرَّمَةٍ
  </aya>
		<aya id="14">
   مَّرْفُوعَةٍ مُّطَهَّرَةٍ
  </aya>
		<aya id="15">
   بِأَيْدِي سَفَرَةٍ
  </aya>
		<aya id="16">
   كِرَامٍ بَرَرَةٍ
  </aya>
		<aya id="17">
   قُتِلَ الْإِنسَانُ مَا أَكْفَرَهُ
  </aya>
		<aya id="18">
   مِنْ أَيِّ شَيْءٍ خَلَقَهُ
  </aya>
		<aya id="19">
   مِن نُّطْفَةٍ خَلَقَهُ فَقَدَّرَهُ
  </aya>
		<aya id="20">
   ثُمَّ السَّبِيلَ يَسَّرَهُ
  </aya>
		<aya id="21">
   ثُمَّ أَمَاتَهُ فَأَقْبَرَهُ
  </aya>
		<aya id="22">
   ثُمَّ إِذَا شَاء أَنشَرَهُ
  </aya>
		<aya id="23">
   كَلَّا لَمَّا يَقْضِ مَا أَمَرَهُ
  </aya>
		<aya id="24">
   فَلْيَنظُرِ الْإِنسَانُ إِلَى طَعَامِهِ
  </aya>
		<aya id="25">
   أَنَّا صَبَبْنَا الْمَاء صَبًّا
  </aya>
		<aya id="26">
   ثُمَّ شَقَقْنَا الْأَرْضَ شَقًّا
  </aya>
		<aya id="27">
   فَأَنبَتْنَا فِيهَا حَبًّا
  </aya>
		<aya id="28">
   وَعِنَبًا وَقَضْبًا
  </aya>
		<aya id="29">
   وَزَيْتُونًا وَنَخْلًا
  </aya>
		<aya id="30">
   وَحَدَائِقَ غُلْبًا
  </aya>
		<aya id="31">
   وَفَاكِهَةً وَأَبًّا
  </aya>
		<aya id="32">
   مَّتَاعًا لَّكُمْ وَلِأَنْعَامِكُمْ
  </aya>
		<aya id="33">
   فَإِذَا جَاءتِ الصَّاخَّةُ
  </aya>
		<aya id="34">
   يَوْمَ يَفِرُّ الْمَرْءُ مِنْ أَخِيهِ
  </aya>
		<aya id="35">
   وَأُمِّهِ وَأَبِيهِ
  </aya>
		<aya id="36">
   وَصَاحِبَتِهِ وَبَنِيهِ
  </aya>
		<aya id="37">
   لِكُلِّ امْرِئٍ مِّنْهُمْ يَوْمَئِذٍ شَأْنٌ يُغْنِيهِ
  </aya>
		<aya id="38">
   وُجُوهٌ يَوْمَئِذٍ مُّسْفِرَةٌ
  </aya>
		<aya id="39">
   ضَاحِكَةٌ مُّسْتَبْشِرَةٌ
  </aya>
		<aya id="40">
   وَوُجُوهٌ يَوْمَئِذٍ عَلَيْهَا غَبَرَةٌ
  </aya>
		<aya id="41">
   تَرْهَقُهَا قَتَرَةٌ
  </aya>
		<aya id="42">
   أُوْلَئِكَ هُمُ الْكَفَرَةُ الْفَجَرَةُ
  </aya>
	</sura>
	<sura nb_aya="29" id="81" name="التكوير">
		<aya id="1">
   إِذَا الشَّمْسُ كُوِّرَتْ
  </aya>
		<aya id="2">
   وَإِذَا النُّجُومُ انكَدَرَتْ
  </aya>
		<aya id="3">
   وَإِذَا الْجِبَالُ سُيِّرَتْ
  </aya>
		<aya id="4">
   وَإِذَا الْعِشَارُ عُطِّلَتْ
  </aya>
		<aya id="5">
   وَإِذَا الْوُحُوشُ حُشِرَتْ
  </aya>
		<aya id="6">
   وَإِذَا الْبِحَارُ سُجِّرَتْ
  </aya>
		<aya id="7">
   وَإِذَا النُّفُوسُ زُوِّجَتْ
  </aya>
		<aya id="8">
   وَإِذَا الْمَوْؤُودَةُ سُئِلَتْ
  </aya>
		<aya id="9">
   بِأَيِّ ذَنبٍ قُتِلَتْ
  </aya>
		<aya id="10">
   وَإِذَا الصُّحُفُ نُشِرَتْ
  </aya>
		<aya id="11">
   وَإِذَا السَّمَاء كُشِطَتْ
  </aya>
		<aya id="12">
   وَإِذَا الْجَحِيمُ سُعِّرَتْ
  </aya>
		<aya id="13">
   وَإِذَا الْجَنَّةُ أُزْلِفَتْ
  </aya>
		<aya id="14">
   عَلِمَتْ نَفْسٌ مَّا أَحْضَرَتْ
  </aya>
		<aya id="15">
   فَلَا أُقْسِمُ بِالْخُنَّسِ
  </aya>
		<aya id="16">
   الْجَوَارِ الْكُنَّسِ
  </aya>
		<aya id="17">
   وَاللَّيْلِ إِذَا عَسْعَسَ
  </aya>
		<aya id="18">
   وَالصُّبْحِ إِذَا تَنَفَّسَ
  </aya>
		<aya id="19">
   إِنَّهُ لَقَوْلُ رَسُولٍ كَرِيمٍ
  </aya>
		<aya id="20">
   ذِي قُوَّةٍ عِندَ ذِي الْعَرْشِ مَكِينٍ
  </aya>
		<aya id="21">
   مُطَاعٍ ثَمَّ أَمِينٍ
  </aya>
		<aya id="22">
   وَمَا صَاحِبُكُم بِمَجْنُونٍ
  </aya>
		<aya id="23">
